version: "3.2"
services:
  uwsgi:
    image: test_uwsgi
    build:
      context: .
    command: uwsgi --http 0.0.0.0:9090 --wsgi-file server.py --callable app
    env_file: server.env
    volumes:
      - ./:/app
    ports:
      - "9090:9090"
  flask:
    image: test_uwsgi
    build:
      context: .
    command: flask run -h 0.0.0.0 -p 9091
    environment:
      FLASK_APP: server.py
    env_file: server.env
    volumes:
      - ./:/app
    ports:
      - "9091:9091"
